### ISSUE TITLE
Search history should be hidden if you navigate away from search

### ISSUE THREAD

**Issue by orezhko** [Microsoft/EmbeddedSocial-iOS-SDK#556] opened 2017-10-13 15:57 UTC
1) open search screen
2) see search history
3) open menu and your profile

Actual result: See profile page together with search history
Expected: See only profile page

**Comment by Vadim-Bulavin** [comment] 2017-10-17 15:12
@orezhko Can't reproduce in `0a6a9009f8c40eb90e8c2a8358ed9ce30c6c111f`

**Comment by Vadim-Bulavin** [comment] 2017-10-23 14:01
@orezhko I think it was fixed by some other commit.

**Closed** 2017-10-23 14:22 UTC
Labels: bug
