### ISSUE TITLE
The application crashes after scrolling posts in search results

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#408] opened 2017-09-29 15:21 UTC
1, Open "Search" screen
2, Enter search criterion that has search results and tap on "Search" button
3. Scroll down and up the list with test results
4. Pull down the screen to update
5. Open a post
6. Navigate back to search results
7. Pull down the screen to update
8. Repeat steps 3-7 several times

Actual Result: The application crashes
Expected Result: All operations are performed as expected

**Comment by Vadim-Bulavin** [comment] 2017-10-02 11:27
@JaroslawRomanovich @IgorPopov-MS I've debugged the issue and it occurs in Feed Module. Please see the stack trace and screenshot below. Based on the stack trace I assume that it's connected with Scroll View offset.

```
0   ???                                 0x000000011e42b057 0x0 + 4802654295
1   EmbeddedSocial-Example              0x000000010882a0f0 main + 0
2   UIKit                               0x000000010b1284c7 -[UIScrollView(UIScrollViewInternal) _notifyDidScroll] + 163
3   UIKit                               0x000000010b111490 -[UIScrollView setContentOffset:] + 539
4   UIKit                               0x000000010b116021 -[UIScrollView _updatePanGesture] + 2464
5   UIKit                               0x000000010b572f59 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
6   UIKit                               0x000000010b57ad57 _UIGestureRecognizerSendTargetActions + 109
7   UIKit                               0x000000010b57870b _UIGestureRecognizerSendActions + 225
8   UIKit                               0x000000010b5779ce -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 981
9   UIKit                               0x000000010b564152 _UIGestureEnvironmentUpdate + 1219
10  UIKit                               0x000000010b563c43 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 484
11  UIKit                               0x000000010b562e0a -[UIGestureEnvironment _updateGesturesForEvent:window:] + 274
12  UIKit                               0x000000010b0aeeea -[UIWindow sendEvent:] + 4092
13  UIKit                               0x000000010b05ba84 -[UIApplication sendEvent:] + 352
14  UIKit                               0x000000010b83f5d4 __dispatchPreprocessedEventFromEventQueue + 2926
15  UIKit                               0x000000010b837532 __handleEventQueue + 1122
16  CoreFoundation                      0x000000010df52c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
17  CoreFoundation                      0x000000010df380cf __CFRunLoopDoSources0 + 527
18  CoreFoundation                      0x000000010df375ff __CFRunLoopRun + 911
19  CoreFoundation                      0x000000010df37016 CFRunLoopRunSpecific + 406
20  GraphicsServices                    0x00000001107daa24 GSEventRunModal + 62
21  UIKit                               0x000000010b03e134 UIApplicationMain + 159
22  EmbeddedSocial-Example              0x000000010882a127 main + 55
23  libdyld.dylib                       0x00000001116b565d start + 1
24  ???                                 0x0000000000000001 0x0 + 1

```

<img width="1552" alt="screen shot 2017-10-02 at 14 25 38" src="https://user-images.githubusercontent.com/29773899/31075323-9dc6d7d8-a77d-11e7-8d2a-b321a2b327cd.png">

**Comment by orezhko** [comment] 2017-10-04 14:12
Jaroslaw, could you please try to reproduce this issue on the latest build from develop

**Comment by IgorPopov-MS** [comment] 2017-10-23 14:01
Closing, since its a the issue for #487. Confirmed by @JaroslawRomanovich .

**Closed by IgorPopov-MS** 2017-10-23 14:01 UTC
Labels: bug, high
